### ISSUE TITLE
[Feature Request] Add feature like switch.vim and make it more configuration 

### ISSUE THREAD

**Issue by samhvw8** [zegervdv/nrpattern.nvim#2]
Add feature like switch.vim and make it more configuration 
https://github.com/AndrewRadev/switch.vim

**Comment by zegervdv** [comment]
Thanks for the suggestion!

I'm not familiar with the plugin, so I need some time to look into it.

The replacement of words in a cyclic pattern is already available. If your cursor is on `true` then pressing `<c-a>` will update it to `false`.
You can define more patterns like this:
``` lua
local defaults = require"nrpattern.default"
defaults[{"yes", "no"}] = {
    priority = 10,
}
```

The other features Switch.vim provides seem a little out of scope for this plugin. 
I already doubted wether to add the cyclic patterns, because they are already a stretch from the original purpose of this plugin.
I like to keep things simple.

I'll keep it in mind and see if I can add it without complicating this plugin too much.

**Comment by samhvw8** [comment]
Thank you for answer, 
Can u add this to readme or doc for other people can easy to find resource ?

**Comment by zegervdv** [comment]
Will do

**Comment by zegervdv** [comment]
Pushed some clarifications to the README and docs
